name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: print test message
        run: echo "hello from github actions"

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./LocalRagAPI.csproj

      - name: Build project
        run: dotnet build ./LocalRagAPI.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish ./LocalRagAPI.csproj --configuration Release --output ./publish --no-build